CREATE VIEW DB.mart_mkt_bx_leads AS
SELECT count(l.ID) as LEADS,
    toDate(DATE_CREATE) AS DT,
    UTM_CAMPAIGN_ID,
    UTM_CAMPAIGN_PURE,
    UTM_SOURCE_PURE,
    UTM_MEDIUM_PURE
FROM DB.mart_mkt_bx_crm_lead as l
GROUP BY UTM_CAMPAIGN_PURE,UTM_CAMPAIGN_ID,UTM_SOURCE_PURE,UTM_MEDIUM_PURE,DT

SETTINGS join_use_nulls = 1